sudo: required
language: java
jdk: oraclejdk8
node_js:
- 8.5.0
services:
- docker
install: true
env:
  local:
    maven:
    - repository=$HOME/.m2

before_install:
- openssl aes-256-cbc -K $encrypted_d49bee1cc322_key -iv $encrypted_d49bee1cc322_iv -in codesigning.asc.enc -out codesigning.asc -d
- gpg --fast-import codesigning.asc

cache:
  directories:
  - "$HOME/.m2"

before_script:

script:
  - mvn clean install
  
deploy:
  - provider: script
    skip_cleanup: true
    script: mvn deploy -Dmaven.test.skip=true --settings travis-maven-settings.xml -Dsettings.security=travis-maven-settings-security.xml -B
    on:
      branch: development
  
  - provider: script
    skip_cleanup: true
    script: mvn release:clean release:prepare -Prelease-sign-artifacts -DautoVersionSubm --settings travis-maven-settings.xml -Dsettings.security=travis-maven-settings-security.xml -B
    on:
      branch: master
      tags: true